[package]
name = "leo-lang"
version = "1.0.7"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "The Leo programming language"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/leo"
keywords = [
  "aleo",
  "cryptography",
  "leo",
  "programming-language",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "web-programming" ]
include = [ "Cargo.toml", "leo", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2018"

[lib]
path = "leo/lib.rs"

[[bin]]
name = "leo"
path = "leo/main.rs"

[workspace]
members = [
  "ast",
  "compiler",
  "core",
  "gadgets",
  "grammar",
  "imports",
  "input",
  "linter",
  "package",
  "state",
  "symbol-table",
  "type-inference"
]

[dependencies.leo-ast]
path = "./ast"
version = "1.0.7"

[dependencies.leo-compiler]
path = "./compiler"
version = "1.0.7"

[dependencies.leo-gadgets]
path = "./gadgets"
version = "1.0.7"

[dependencies.leo-imports]
path = "./imports"
version = "1.0.7"

[dependencies.leo-input]
path = "./input"
version = "1.0.7"

[dependencies.leo-package]
path = "./package"
version = "1.0.7"

[dependencies.leo-state]
path = "./state"
version = "1.0.7"

[dependencies.snarkos-algorithms]
version = "1.1.3"
default-features = false

[dependencies.snarkos-curves]
version = "1.1.3"
default-features = false

[dependencies.snarkos-errors]
version = "1.1.3"
default-features = false

[dependencies.snarkos-gadgets]
version = "1.1.3"
default-features = false

[dependencies.snarkos-models]
version = "1.1.3"
default-features = false

[dependencies.snarkos-utilities]
version = "1.1.3"

[dependencies.clap]
version = "2.33.3"

[dependencies.colored]
version = "2.0"

[dependencies.dirs]
version = "3.0.1"

[dependencies.console]
version = "0.13.0"

[dependencies.dotenv]
version = "0.15.0"

[dependencies.env_logger]
version = "0.8"

[dependencies.from-pest]
version = "0.3.1"

[dependencies.lazy_static]
version = "1.4.0"

[dependencies.notify]
version = "4.0.15"

[dependencies.num-bigint]
version = "0.3"

[dependencies.rand]
version = "0.8"

[dependencies.rand_core]
version = "0.6.0"

[dependencies.reqwest]
version = "0.10.10"
features = [ "blocking", "json" ]

[dependencies.self_update]
version = "0.22.0"
features = [ "archive-zip" ]

[dependencies.serde]
version = "1.0"
features = [ "derive" ]

[dependencies.serde_json]
version = "1.0"

[dependencies.thiserror]
version = "1.0"

[dependencies.toml]
version = "0.5"

[dependencies.tracing]
version = "0.1"

[dependencies.tracing-subscriber]
version = "0.2"
features = [ "fmt" ]

[dependencies.zip]
version = "0.5"

[dev-dependencies.rusty-hook]
version = "0.11.2"

[features]
default = [ ]
ci_skip = [ "leo-compiler/ci_skip" ]

[profile.release]
opt-level = 3
lto = "thin"
incremental = true

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = "thin"
incremental = true
debug-assertions = false

[profile.dev]
opt-level = 0

[profile.test]
opt-level = 0
debug-assertions = true
debug = true
